FF-ONLY Version 0.2.0.
scala-js/scala-js-env-selenium pull request #78
Opened 2017-08-02 04:25 UTC by gzm0

2017-08-02 05:30 UTC, gzm0 commented
Blocked by #79.

2017-08-04 05:26 UTC, gzm0 commented
Good for review now. Review by @sjrd

2017-08-04 06:05 UTC, sjrd requested changes

2017-08-04 06:05 UTC, sjrd commented on README.md
> +[![Scala.js](https://www.scala-js.org/assets/badges/scalajs-0.6.18.svg)](https://www.scala-js.org/)
That badge does not exist because 0.6.18 was forward compatible with 0.6.17.

2017-08-04 06:05 UTC, sjrd commented on README.md
> +You are responsible to install the [drivers](
I think this should be "responsible for installing", shouldn't it?

2017-08-04 06:22 UTC, gzm0 commented on README.md
> +You are responsible to install the [drivers](
Yes, probably.

2017-08-04 06:22 UTC, gzm0 commented on README.md
> +[![Scala.js](https://www.scala-js.org/assets/badges/scalajs-0.6.18.svg)](https://www.scala-js.org/)
Ah :) even the `JSEnv` API? (it's probably fine :P)

2017-08-04 06:22 UTC, gzm0 commented
Updated

2017-08-04 07:49 UTC, sjrd approved these changes

2017-08-04 07:50 UTC, sjrd commented
I'll fast-forward, tag, publish, etc. ;)

2017-08-04 08:05 UTC, merged