DO NOT MERGE Better materialization API
scala-js/scala-js-env-selenium pull request #90
Opened 2018-07-09 18:40 UTC by gzm0

2018-07-12 09:49 UTC, sjrd requested changes

2018-07-12 09:49 UTC, sjrd commented on seleniumJSEnv/src/main/scala/org/scalajs/jsenv/selenium/SeleniumJSEnv.scala
> +    def withMaterializeInServer(contentDir: Path, webRoot: URL): Config =
The Scaladoc attached to this method has an example where the parameters are `String`s. It should be changed to use a `Path` and a `URL` instead.

2018-07-18 18:47 UTC, gzm0 commented on seleniumJSEnv/src/main/scala/org/scalajs/jsenv/selenium/SeleniumJSEnv.scala
> +    def withMaterializeInServer(contentDir: Path, webRoot: URL): Config =
I have inverted the order and given both methods an individual Scaladoc. I didn't want to change the example, because it is probably the most common usage of this.

2018-07-18 19:13 UTC, sjrd approved these changes

2018-07-18 19:13 UTC, merged