CI ONLY organize tests
scala-js/scala-js-env-selenium pull request #91
Opened 2018-07-19 08:59 UTC by gzm0

2018-07-21 10:48 UTC, sjrd requested changes

2018-07-21 10:48 UTC, sjrd commented on build.sbt
> +      baseDirectory.value.getParentFile / "project/TestCapabilities.scala",
We usually do this the other way around. We put the source file in the normal source folder of the project (so in `scalajs-env-selenium/src/test/scala/...`) and we add the `sources +=` in `project/plugins.sbt`. It has at least one concrete advantage: IDEs are happier with it.

2018-07-22 15:43 UTC, gzm0 commented
Updated.

2018-07-22 15:58 UTC, sjrd approved these changes

2018-07-22 16:20 UTC, merged